with open('src/dashboard/web/index.html', 'r', encoding='utf-8') as f:
    c = f.read()
print('File size:', len(c))
print('Has local vendor:', '/vendor/three/three.module.js' in c)
print('Has unpkg:', 'unpkg.com' in c)
print('Has jsdelivr:', 'jsdelivr' in c)
print('Has ctl-group harness:', 'ctl-group harness' in c)
print('Has sliders:', 'sliders:' in c)
print('Has sliderVals:', 'sliderVals:' in c)
print('Has TwinAPI:', 'TwinAPI' in c)
print('Has __twin:', '__twin' in c)
print('Has btn-play:', 'btn-play' in c)
print('Has SIMULATION CONTROLS:', 'SIMULATION CONTROLS' in c)
print('Has bar.innerHTML:', 'bar.innerHTML' in c)
print('Has data-ctl storm:', 'data-ctl="storm"' in c)
