import assert from 'node:assert/strict';
import {TwinAPI} from '../src/dashboard/web/api.js';
import {guideFor,mcmDay,escapeHTML,reserveMessage} from '../src/dashboard/web/presentation.js';

globalThis.window={location:{protocol:'http:',host:'localhost'}};
globalThis.WebSocket=class {static OPEN=1;constructor(){this.readyState=0;}};
globalThis.setTimeout=()=>0;
globalThis.setInterval=()=>({unref(){}});
globalThis.clearTimeout=()=>{};
let frame={state_identity:{state_id:'step0-t0',sim_step_index:0,network_timestep:0},simulation:{running:false,speed:1},controller_mode:'MANUAL'};
let fail=false,rejectCommand=false;
const requests=[],states=[],statuses=[],feedback=[];
globalThis.fetch=async(url,options={})=>{
  requests.push({url,method:options.method,body:options.body});
  if(fail)throw Error('Backend offline');
  if(options.method==='POST')return {ok:!rejectCommand,status:rejectCommand?409:200,json:async()=>({status:rejectCommand?'rejected':'success'})};
  return {ok:true,json:async()=>frame};
};
const api=new TwinAPI(s=>states.push(s),s=>statuses.push(s),s=>feedback.push(s));
await new Promise(resolve=>setImmediate(resolve));
await api.checkFreshness();
assert.equal(statuses.at(-1),'CONNECTED');
assert.equal(states.at(-1),frame);
assert.equal(api.transport,'REST');
api.ws.onerror();api.ws.onclose();
assert.equal(statuses.at(-1),'CONNECTED','WebSocket failure must not disconnect a healthy REST backend');
frame={...frame,state_identity:{state_id:'step1-t1',sim_step_index:1,network_timestep:1}};
await api.setGate('reservoir_1',50);
assert.equal(states.at(-1).state_identity.state_id,'step1-t1');
assert.equal(feedback.at(-1),'ACCEPTED · application shown by backend state');
assert.equal(JSON.parse(requests.find(r=>r.url.includes('/gate/')).body).value,50);
assert.equal(api.acceptState({state_identity:{state_id:'old',sim_step_index:0}},'REST'),false);
assert.equal(api.lastStateId,'step1-t1','Old transport frames cannot regress the simulation');
rejectCommand=true;
await api.setGate('reservoir_1',100);
assert.equal(feedback.at(-1),'COMMAND REJECTED (409)');
rejectCommand=false;fail=true;
await api.checkFreshness();
assert.notEqual(statuses.at(-1),'CONNECTED');
assert.equal(mcmDay(1e6/86400),1);
assert.equal(mcmDay(null),null);
assert.equal(escapeHTML('<img>'),'&lt;img&gt;');
assert.equal(guideFor({classroom_demo:{active:true,day:2},controller_mode:'MANUAL'})[0],'03 / ROUTING DELAY');
assert.equal(guideFor({classroom_demo:{active:true,day:4},controller_mode:'MANUAL'})[0],'04 / COORDINATED CONTROL');
assert.equal(guideFor({classroom_demo:{active:true,day:5},controller_mode:'AI'})[0],'04 / COORDINATED CONTROL');
assert.match(reserveMessage({controller_mode:'AI'}),/awaiting/);
const reserveCheck={mode:'AI',storage_reserve:{enabled:true,verified:true,fraction:.3}};
assert.match(reserveMessage({controller_mode:'AI',final_safety:reserveCheck}),/30%.*actual daily inflow/);
assert.match(reserveMessage({controller_mode:'MANUAL',final_safety:reserveCheck}),/inactive/);
assert.match(reserveMessage({controller_mode:'AI',final_safety:{...reserveCheck,mode:'MANUAL'}}),/awaiting/);
console.log('Presentation transport regression checks passed.');
